// export * from './setup/address';
// export * from './setup/facility';
export * from './setup/gender';
export * from './setup/title';
export * from './setup/maritalstatus';
export * from './setup/user';
// export * from './setup/person';
export * from './setup/country';
export * from './setup/patient';
export * from './setup/relationship';
export * from './setup/profession';
export * from './setup/personprincipal';
export * from './setup/persondependant';
export * from './setup/corporatefacility';
export * from './setup/familyhealthcover';
export * from './setup/companyhealthcover';
export * from './setup/facilityservice';
export * from './setup/beneficiary';
export * from './setup/hia';
export * from './setup/care-provider';
// export * from './setup/employer';


export * from './organisation/address';
export * from './organisation/bank-detail';
export * from './organisation/contact';
export * from './organisation/employer';
export * from './organisation/facility';
export * from './organisation/hia';
export * from './organisation/provider';
export * from './plan/Plan';
export * from './person/person';
export * from './person/image';
export * from './person/next-of-kin';
export * from './claim/claim';
