export interface CareProvider {
    name: string,
    email: string,
    contactPhoneNo: string,
    contactFullName: string,
    departments?: any,
    facilityOwnershipId: string,
    facilityTypeId?: string,
    facilityClassId?: string,
    lshmClassification: any,
    logo?: string,
    logoObject?: any,
    bankDetails: any,
    facilitymoduleId?: any,
    isTokenVerified: boolean,
    isLshma: Boolean,
    address: any,
    questionaire?: any,
    minorLocations?: any,
    lasrraId: string,
    hefeemaNo: string,
    hefeemaStatus: string,
    gradeId: string,
    verificationToken?: string,
}